name: Main workflow

on: [push, pull_request]

jobs:
  tests:
    name: Tests & Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check with linters
      run: tox -e lint
    - name: Test with tox
      run: tox -e py

  build:
    name: Build and upload release to Pypi
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    # deploy only when a new tag is pushed to github
    - name: Publish package distributions to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
